'''
Database Models
=================
Defines the PostgreSQL schema using SQLAlchemy ORM. 
Each class = one table. Each class attribute = one column.

Why ORM instead of raw SQL?
- Type safety: column types are enforced in Python
- Portability: swap PostgreSQL for SQLite in tests without changing code
- Maintainability: schema lives alongside the code that uses it
'''

from datetime import datetime, timezone
from sqlalchemy import (
    Boolean, Column, DateTime, Float, 
    Integer, String, Text, create_engine
)
from sqlalchemy.orm import declarative_base, sessionmaker

# Base is the registry that tracks all our model classes
# Every model class inherits from it - SQLAlchemy uses this
# to know which classes represent database tables.
Base = declarative_base()


class LogEvent(Base):
    '''
    Stores every individual log event consumed from Kafka.
    One row = one log line from one microservice.
    '''
    __tablename__ = 'log_events'

    id          = Column(Integer, primary_key=True, autoincrement=True)
    event_id    = Column(String(36), unique=True, nullable=False, index=True)  
    # index=True on event_id: we'll query by this often. An index makes
    # lookups 0(log n) instead of O(n) - critical at scale.

    timestamp   = Column(DateTime(timezone=True), nullable=False, index=True) 
    service     = Column(String(50), nullable=False, index=True)
    level       = Column(String(10), nullable=False) # INFO, WARN, ERROR 
    endpoint    = Column(String(100))
    status_code = Column(Integer)
    latency_ms  = Column(Float)
    user_id     = Column(String(36))
    ip_address  = Column(String(45)) # 45 chars supports IPv6
    message     = Column(Text)
    fault_injected = Column(Boolean, default=False) # True if this log was generated by our fault injection tests

    # We inserted this row as its useful for pipeline lag monitoring
    ingested_at = Column(
        DateTime(timezone=True), 
        default=lambda: datetime.now(timezone.utc)
    )

    def __repr__(self):
        return (
            f"<LogEvent service={self.service} level={self.level} "
            f"status={self.status_code} latency={self.latency_ms}ms>"
        )
    

class AnomalyAlert(Base):
    '''
    Stores anomaly scores for each 30-second window.
    One row = one analyzed time window for one service.

    Why store windows separately from raw logs?
    The dashboard and API need to answer different questons:
    - "Show me recent logs" -> query log_events
    - "Show me anomaly scores over time" -> query anomaly_alerts
    Separating them keeps both queries fast.
    '''
    __tablename__ = 'anomaly_alerts'

    id              = Column(Integer, primary_key=True, autoincrement=True)
    window_start    = Column(DateTime(timezone=True), nullable=False, index=True)
    window_end      = Column(DateTime(timezone=True), nullable=False)
    service         = Column(String(50), nullable=False, index=True)

    # ── Extracted features (what Isolation Forest sees) ──────────
    event_count     = Column(Integer)      # Total logs in this window
    error_rate      = Column(Float)        # fraction that were ERROR/WARN
    avg_latency_ms  = Column(Float)        
    p95_latency_ms  = Column(Float)        # 95th percentile latency
    p99_latency_ms  = Column(Float)        # 99th percentile - catches tail latency
    error_count     = Column(Integer)      
    warn_count      = Column(Integer)
    status_5xx_rate = Column(Float)        # fraction of logs with 5xx status codes

    # ── Isolation Forest output ───────────────────────────────────
    anomaly_score   = Column(Float)        
    # score < 0 = anomalous. More negative = more anomalous.
    # IsolationForest.score_samples() returns neative values for anomalies
    # (confusingly, lower = worse). We store the raw score.

    is_anomaly      = Column(Boolean)
    # True when score falls below our contamination threshold

    explanation     = Column(Text)
    # LLM-generated plain English explanation (filled in by API layer)

    created_at     = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc)
    )

    def __repr__(self):
        return (
            f"<AnomalyAlert service={self.service} "
            f"score={self.anomaly_score:.3f} is_anomaly={self.is_anomaly}>"
        )

# ── Database Connection Factory ───────────────────────────────────
def get_engine(database_url: str):
    """
    Create a SQLAlchemy engine.

    pool_pre_ping=True: before using a connection from the pool,
    test it with a cheap query. Prevents 'stale connection' errors
    after PostgreSQL restarts — common in Docker environments.
    """
    return create_engine(database_url, pool_pre_ping=True)


def get_session_factory(engine):
    """
    Returns a Session class bound to our engine.
    Call session_factory() to get a new session (= a DB transaction).

    Why a factory? We want one engine (shared connection pool)
    but many short-lived sessions (one per operation).
    """
    return sessionmaker(bind=engine, autocommit=False, autoflush=False)


def init_db(engine) -> None:
    """Create all tables if they don't exist yet."""
    Base.metadata.create_all(engine)

